### ISSUE TITLE
Do you consider updating the latest three.js to support more model formats for loading and viewing?

### ISSUE THREAD

**Issue by jiawenquan** [saaratrix/generic-3Dproduct-viewer#1]
This is an amazing project, beautiful code,
Do you consider updating the latest three.js to support more model formats for loading and viewing?

**Comment by haestflod** [comment]
It's using the latest three.js version on npm which currently is r104.
As for more model formats. I'm using the three.js examples loaders to load .obj and .gltf and the examples support many more file formats but you'd have to update them to support ES6 modules for import.

**Comment by jiawenquan** [comment]
Thank you for your help. I try to manually update the latest load modules of three. js

**Comment by saaratrix** [comment]
Updated to r109 which is the latest support and it has full ES6 support now so much easier to add more loaders for different file formats.
